server.port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/car-rental-billing-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  kafka.consumer.group-id: billing-service