server.port: 8085

spring:
  profiles:
    default: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: andrew.s.titov@gmail.com
    password: abcdefghijklmnop
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  kafka.consumer.group-id: mail-service

security:
  email-verification.ttl-hours: 3
  reset-password.ttl-minutes: 10

mail:
  from: noreply@minskcarrental.by
  app-name: Minsk Car Rental
  template:
    arg:
      message-parts: messageParts
      links: links
      logo: logo

external:
  url:
    user-service:
      email-by-id:        http://user-service/user/email
      email-verification: http://auth-token-service/auth/verify
      new-password:       http://auth-token-service/auth/password_reset
    booking-service:
      booking-info:       http://booking-service/booking
    car-service:
      short-info:         http://car-service/car/{carId}/short